NewsPaper/NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('news/', include('news.urls')),
]

NewsPaper/NewsPaper/news/urls.py
from django.urls import path
from .views import (NewsList, NewDetail, NewsSearch, NewsCreate,
                    NewsEdit, NewsDelete, CategoryList, subscribe,
                    delete_subscribe, upgrade_user)
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('', cache_page(60)(NewsList.as_view()), name='news_list'),
    path('<int:pk>/', NewDetail.as_view(), name='new_detail'),
    path('search/', NewsSearch.as_view(), name='news_search'),
    path('create/', NewsCreate.as_view(), name='news_create'),
    path('<int:pk>/edit/', NewsEdit.as_view(), name='new_edit'),
    path('<int:pk>/delete/', NewsDelete.as_view(), name='new_delete'),
    path('categories/<int:pk>/', CategoryList.as_view(), name='category_news'),
    path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),
    path('categories/<int:pk>/unsubscribe', delete_subscribe, name='delete_subscribe'),
    path('upgrade/', upgrade_user, name='account_upgrade'),
]

NewsPaper/NewsPaper/news/models.py
from django.core.cache import cache
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    authorRating = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.authorRating = (pRat * 3) + cRat
        self.save()

    def __str__(self):
        return f'{self.authorUser}'

    @property
    def rating(self):
        return self.authorRating


class Category(models.Model):
    name_category = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories')

    def __str__(self):
        return f'{self.name_category}'


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    ARTICLE = 'AR'
    NEWS = 'NW'
    CATEGORIES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    )
    publication = models.CharField(max_length=2, choices=CATEGORIES, default=NEWS)
    date_creation = models.DateTimeField(auto_now_add=True)
    post_category = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=256)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def preview(self):
        if len(self.text) > 128:
            return f'{self.text[0:128]}...'
        return f'{self.text}'

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return f'/news/{self.id}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)   # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'post-{self.pk}')


class PostCategory(models.Model):
    post_through = models.ForeignKey(Post, on_delete=models.CASCADE)
    category_through = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.post_through}'


class Comment(models.Model):
    comment_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    date_creation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'{self.comment_post}'

NewsPaper/NewsPaper/news/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Post


class NewsForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['publication',
                  'title',
                  'text',
                  'post_category',
                  ]

    def clean_name(self):
        title = self.cleaned_data["title"]
        if title[0].islower():
            raise ValidationError(
                "Название должно начинаться с заглавной буквы"
            )
        return title

NewsPaper/NewsPaper/news/views.py
from django.conf import settings

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import User, Group
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import (ListView, DetailView, CreateView, UpdateView, DeleteView)

from .forms import NewsForm
from .models import Post, Category, Author
from .filters import PostFilter

from datetime import datetime, timedelta, timezone
from django.utils import timezone

from django.urls import reverse_lazy
from django.core.cache import cache


class NewsList(ListView):
    model = Post
    ordering = '-date_creation'
    template_name = 'news.html'
    context_object_name = 'news'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        limit = settings.DAY_LIMIT_POSTS
        today = timezone.now()
        prev_day = today - timedelta(hours=24)
        posts_day_count = Post.objects.filter(date_creation__gte=prev_day, author__authorUser=user).count()
        context['posts_limit'] = limit <= posts_day_count
        context['limit'] = limit
        context['count'] = posts_day_count
        context['date_creation'] = datetime.utcnow()
        context['is_author'] = self.request.user.groups.filter(name='authors').exists()
        return context


class NewDetail(DetailView):
    model = Post
    template_name = 'new.html'
    context_object_name = 'new'
    queryset = Post.objects.all()

    def get_object(self, *args, **kwargs):  # переопределяем метод получения объекта
        obj = cache.get(f'post-{self.kwargs["pk"]}', None)  # кэш похож на словарь и метод get действует также
        # Он забирает значение по ключу, если его нет, то забирает None

        # если объекта нет в кэше, то получаем его и записывает в кэш
        if not obj:
            obj = super().get_object(queryset=self.queryset)
            cache.set(f'post-{self.kwargs["pk"]}', obj)

        return obj


class NewsSearch(ListView):
    model = Post
    ordering = '-date_creation'
    template_name = 'news_search.html'
    context_object_name = 'news'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class NewsCreate(PermissionRequiredMixin, CreateView):
    permission_required = ('news.add_post',)
    form_class = NewsForm
    model = Post
    template_name = 'new_edit.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = Author.objects.get(authorUser=self.request.user)
        return super().form_valid(form)


class NewsEdit(PermissionRequiredMixin, UpdateView):
    permission_required = ('news.edit_post',)
    form_class = NewsForm
    model = Post
    template_name = 'new_edit.html'


class NewsDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('news.delete_post',)
    model = Post
    template_name = 'new_delete.html'
    success_url = reverse_lazy('news_list')


class CategoryList(ListView):
    model = Post
    template_name = 'category_list.html'
    context_object_name = 'category_news'
    paginate_by = 10

    def get_queryset(self):
        self.post_category = get_object_or_404(Category, id=self.kwargs['pk'])
        queryset = Post.objects.filter(post_category=self.post_category).order_by('-date_creation')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_subscriber'] = self.request.user not in self.post_category.subscribers.all()
        context['category'] = self.post_category
        return context


@login_required
def subscribe(request, pk):  # Подписка
    user = request.user
    category = Category.objects.get(id=pk)
    category.subscribers.add(user)

    message = 'You have successfully subscribed to the category news feed:'
    return render(request, 'subscribe.html', {'category': category, 'message': message})


@login_required
def delete_subscribe(request, pk):  # Отписка
    user = request.user
    category = Category.objects.get(id=pk)
    category.subscribers.remove(user)

    message = 'You have successfully unsubscribed from category news feed:'
    return render(request, 'delete_subscribe.html', {'category': category, 'message': message})


@login_required
def upgrade_user(request):
    user = request.user
    group = Group.objects.get(name='authors')
    if not request.user.groups.filter(name='authors').exists():
        group.user_set.add(user)
        if not hasattr(user, 'author'):
            Author.objects.create(
                authorUser=User.objects.get(pk=user.id)
            )
    return redirect('news_list')

NewsPaper/NewsPaper/templates/category_list.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}


{% load custom_filters %}


{% block title %}
News
{% endblock title %}


{% block content %}
<h1>◄ ALL PUBLICATIONS ►</h1>
<h6><i>You see {{ category_news|length }} out of {{ paginator.count }} publications on our News Portal </i></h6>

    {% if is_not_subscriber %}
    <p class="text-center"><a href="{% url 'subscribe' category.id %}" class="btn btn-secondary btn-sm">Subscribe</a></p>
    {% else %}
    <p class="text-center"><a href="{% url 'delete_subscribe' category.id %}" class="btn btn-secondary btn-sm">Unubscribe</a></p>
    {% endif %}

<hr>

    {% if perms.news.add_post %}
    <a href="{% url 'news_create' %}">Add new publication</a>
    {% endif %}

{% if category_news %}
    <table>
           <tr>
               <td>Type of publication</td>
               <td>Title</td>
               <td>Date of publication</td>
               <td>Content</td>
               <td>Category</td>

                {% if perms.news.change_post or perms.news.delete_post %}
                <td>Actions</td>
                {% endif %}
           </tr>

           {% for new in category_news %}
           <tr>
               <td>{{ new.get_publication_display }}</td>
               <td>
                   <a class="nav-link" href="{% url 'new_detail' new.id %}">{{ new.title }}</a>
               </td>
               <td>{{ new.date_creation|date:'d M Y' }}</td>
               <td>{{ new.text|truncatewords:20|censor }}</td>
               <td>{% for category in new.post_category.all %}
                   <a href="{% url 'category_news' category.id %}">{{ category }}</a>
                    {% endfor %}
                   <td>
               <td>
                    {% if perms.news.change_post %}
                    <a href="{% url 'new_edit' pk=new.id %}">Change</a>
                    {% endif %}
                    {% if perms.news.delete_post %}
                    <a href="{% url 'new_delete' new.id %}">Delete</a>
                    {% endif %}
                </td>
           </tr>
           {% endfor %}

       </table>
{% else %}
    <h2>There's no publications!</h2>
   {% endif %}

{# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper/NewsPaper/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Здравствуй! Новые статьи за прошедшую неделю!</h1>
<ul>
  {% for post in posts %}
  <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a></li>
  {% endfor %}
</ul>
</body>
</html>

NewsPaper/NewsPaper/templates/delete_subscribe.html
{% extends 'flatpages/default.html' %}

{% block title %}
    Unsubscribe
{% endblock title %}

{% block content %}
<h1>We'll be glad to see you again in our News Portal!</h1>
<hr>

    <h1 class="text-center">{{ message }} {{ category }} !</h1>
<p></p>
 <p class="text-center"><a href="{% url 'news_list' %}" class="btn btn-secondary btn-sm">See all publications</a></p>
{% endblock content %}

NewsPaper/NewsPaper/templates/new.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}


{% block title %}
New
{% endblock title %}


{% block content %}
<h1>{{ new }}</h1>
<h3>{{ new.date_creation|date:'d M Y' }}</h3>
<hr>
<h2>{{ new.text|censor }}</h2>
{% endblock content %}

NewsPaper/NewsPaper/templates/new_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Здравствуй, {{ name }}! Новая <a href="{{ link }}">статья</a> в твоем любимом разделе!</h1>
<p>{{ text|truncatechars:50 }}</p>
<hr>
</body>
</html>

NewsPaper/NewsPaper/templates/new_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>◄ DELETE PUBLICATION ►</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Do you really want to delete "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper/NewsPaper/templates/new_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>◄ CREATING A PUBLICATION ►</h1>
<hr>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/NewsPaper/templates/news.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}


{% load custom_filters %}


{% block title %}
News
{% endblock title %}


{% block content %}
<h1>◄ ALL PUBLICATIONS ►</h1>
<h6><i>You see {{ news|length }} out of {{ paginator.count }} publications on our News Portal </i></h6>

<hr>

    {% if perms.news.add_post %}
    <a href="{% url 'news_create' %}">Add new publication</a>
    {% endif %}

{% if news %}
    <table>
           <tr>
               <td>Type of publication</td>
               <td>Title</td>
               <td>Date of publication</td>
               <td>Content</td>

                {% if perms.news.change_post or perms.news.delete_post %}
                <td>Actions</td>
                {% endif %}
           </tr>

           {% for new in news %}
           <tr>
               <td>{{ new.get_publication_display }}</td>
               <td>
                   <a class="nav-link" href="{% url 'new_detail' new.id %}">{{ new.title }}</a>
               </td>
               <td>{{ new.date_creation|date:'d M Y' }}</td>
               <td>{{ new.text|truncatewords:20|censor }}</td>
               <td>
                    {% if perms.news.change_post %}
                    <a href="{% url 'new_edit' pk=new.id %}">Change</a>
                    {% endif %}
                    {% if perms.news.delete_post %}
                    <a href="{% url 'new_delete' new.id %}">Delete</a>
                    {% endif %}
                </td>
           </tr>
           {% endfor %}

       </table>
{% else %}
    <h2>There's no publications!</h2>
   {% endif %}

{# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper/NewsPaper/templates/news_search.html
{% extends 'flatpages/default.html' %}


{% load custom_filters %}


{% block title %}
Search
{% endblock title %}


{% block content %}
<h1>◄ SEARCHING FOR PUBLICATIONS ►</h1>
<h6><i>You see {{ news|length }} out of {{ paginator.count }} publications on our News Portal </i></h6>
<hr>
<form action="" method="get">
   {{ filterset.form.as_p }}
   <input type="submit" value="Search" />
</form>
{% if news %}
    <table>
           <tr>
               <td>Type of publication</td>
               <td>Title</td>
               <td>Date of publication</td>
               <td>Content</td>
           </tr>

           {% for new in news %}
           <tr>
               <td>{{ new.publication }}</td>
               <td>{{ new.title|censor }}</td>
               <td>{{ new.date_creation|date:'d M Y' }}</td>
               <td>{{ new.text|truncatewords:20|censor }}</td>
           </tr>
           {% endfor %}

       </table>
{% else %}
    <h2>There's no publications!</h2>
   {% endif %}

{# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper/NewsPaper/templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% block title %}
    Subscribe
{% endblock title %}

{% block content %}
<h1>Thank you for your interest in our News Portal</h1>
<hr>

    <h1 class="text-center">{{ message }} {{ category }} !</h1>
<p></p>
 <p class="text-center"><a href="{% url 'news_list' %}" class="btn btn-secondary btn-sm">See all publications</a></p>
{% endblock content %}